/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package preguntasTest.vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import preguntasTest.clases.Pregunta;
import preguntasTest.clases.Usuario;
import preguntasTest.gestion.Gestion;

/**
 *
 * @author manu1
 */
public class PanelCRUD extends javax.swing.JPanel {
    VentanaPreguntasTest miVentana;
    private Boolean editar;
    private Usuario usuarioAEditar;
    private List<Pregunta> listaPreguntas;
    /**
     * Creates new form PanelCRUD
     */
    public PanelCRUD(VentanaPreguntasTest miVentana, Usuario usuario) {
        initComponents();
        this.miVentana = miVentana;
        this.usuarioAEditar = usuario;
        this.editar = false;
        
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGroup = new javax.swing.ButtonGroup();
        tbOp3 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLeer = new javax.swing.JButton();
        lblPregunta = new javax.swing.JLabel();
        tbPregunta = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        tbOp2 = new javax.swing.JTextField();
        tbOp1 = new javax.swing.JTextField();
        tbOp4 = new javax.swing.JTextField();
        rbtnOp1 = new javax.swing.JRadioButton();
        rbtnOp2 = new javax.swing.JRadioButton();
        rbtnOp3 = new javax.swing.JRadioButton();
        rbtnOp4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaPreguntas = new javax.swing.JList<>();
        lblPreguntas = new javax.swing.JLabel();

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPregunta.setText("Pregunta");
        lblPregunta.setName(""); // NOI18N

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        rbtnGroup.add(rbtnOp1);
        rbtnOp1.setSelected(true);
        rbtnOp1.setText("Opcion 1");

        rbtnGroup.add(rbtnOp2);
        rbtnOp2.setText("Opcion 2");

        rbtnGroup.add(rbtnOp3);
        rbtnOp3.setText("Opcion 3");

        rbtnGroup.add(rbtnOp4);
        rbtnOp4.setText("Opcion 4");

        jScrollPane2.setViewportView(jListaPreguntas);

        lblPreguntas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPreguntas.setText("PREGUNTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPreguntas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPregunta)
                        .addGap(24, 24, 24)
                        .addComponent(tbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnOp2)
                            .addComponent(rbtnOp1)
                            .addComponent(rbtnOp3))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tbOp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnOp4)
                        .addGap(24, 24, 24)
                        .addComponent(tbOp4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLeer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPregunta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnOp1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnOp2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnOp3)
                            .addComponent(tbOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnOp4)
                            .addComponent(tbOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPreguntas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
if (editar) {
            //Gestion.getInstance().editarUsuario(usuarioAEditar, tbNombre.getText().toString(), tbApellido1.getText().toString(), tbApellido2.getText().toString());
            JOptionPane.showMessageDialog(null, "Pregunta editado correctamente.");
            cargarLista();
            
            btnRegistrar.setText("Registrar");
            editar = false;
        }
        else {
            if (tbPregunta.getText().equals("") || tbOp1.getText().equals("") || tbOp2.getText().equals("") || tbOp3.getText().equals("") || tbOp4.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debes introducir todos los valores para poder registrar un usuario.");
            }
            else {
                //insertarPregunta();
                cargarLista();
            }
        }
        
        this.updateUI();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if (jListaPreguntas.getSelectedIndices().length == 0) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar mínimo un usuario para poder eliminarlo.");
        }
        else {
            int[] filas = jListaPreguntas.getSelectedIndices();
            List<Pregunta> preguntas = new ArrayList<Pregunta>();
            
            for (int i = 0; i < filas.length; i++) {
                preguntas.add(listaPreguntas.get(filas[i]));
            }
            
            //Gestion.getInstance().eliminarUsuarios(preguntas);            
            cargarLista();
        }
        
        this.updateUI();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed

    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PanelInicio panel = new PanelInicio(miVentana);

        miVentana.cambiarPanel(panel);
    }//GEN-LAST:event_btnVolverActionPerformed

    public void cargarLista() {
        listaPreguntas = Gestion.getInstance().obtenerPreguntas(usuarioAEditar);

        DefaultListModel modelo = new DefaultListModel();

        for (Pregunta pregunta : listaPreguntas) {
            modelo.addElement(pregunta.getPregunta());
        }

        jListaPreguntas.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JList<String> jListaPreguntas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblPreguntas;
    private javax.swing.ButtonGroup rbtnGroup;
    private javax.swing.JRadioButton rbtnOp1;
    private javax.swing.JRadioButton rbtnOp2;
    private javax.swing.JRadioButton rbtnOp3;
    private javax.swing.JRadioButton rbtnOp4;
    private javax.swing.JTextField tbOp1;
    private javax.swing.JTextField tbOp2;
    private javax.swing.JTextField tbOp3;
    private javax.swing.JTextField tbOp4;
    private javax.swing.JTextField tbPregunta;
    // End of variables declaration//GEN-END:variables
}
