/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package preguntasTest.vista;

import javax.swing.JOptionPane;
import preguntasTest.clases.Usuario;

/**
 *
 * @author Dam
 */
public class PanelInicio extends javax.swing.JPanel {

    private VentanaPreguntasTest miVentana;
    private Usuario usuarioActual;

    /**
     * Creates new form panelInicio
     */
    public PanelInicio(VentanaPreguntasTest miVentana) {
        initComponents();
        this.miVentana = miVentana;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnPregCRUD = new javax.swing.JButton();
        btnUsuCRUD = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo.setText("MOVIDAS TOPE DE TOCHAS QUE NO ENTENDERÉIS");
        lblTitulo.setName("lblTitulo"); // NOI18N

        btnJugar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.setName("btnJugar"); // NOI18N
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        btnPregCRUD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPregCRUD.setText("CRUD Preguntas");
        btnPregCRUD.setName("btnJugar"); // NOI18N
        btnPregCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregCRUDActionPerformed(evt);
            }
        });

        btnUsuCRUD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUsuCRUD.setText("CRUD Usuarios");
        btnUsuCRUD.setName("btnJugar"); // NOI18N
        btnUsuCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuCRUDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnUsuCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnPregCRUD)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnJugar)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuCRUD)
                    .addComponent(btnPregCRUD))
                .addGap(18, 18, 18)
                .addComponent(btnJugar)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        if (miVentana.obtenerUsuario() != null) {
            usuarioActual = miVentana.obtenerUsuario();
            
            PanelPreguntas panel = new PanelPreguntas(miVentana, usuarioActual);
        
            miVentana.cambiarPanel(panel);
        }
        else {
            JOptionPane.showMessageDialog(null, "No ha elegido ningún usuario.");
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnPregCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregCRUDActionPerformed
        if (miVentana.obtenerUsuario() != null) {
            usuarioActual = miVentana.obtenerUsuario();
            
            PanelCRUD panel = new PanelCRUD(miVentana, usuarioActual);
        
            miVentana.cambiarPanel(panel);
        }
        else {
            JOptionPane.showMessageDialog(null, "No ha elegido ningún usuario.");
        }
    }//GEN-LAST:event_btnPregCRUDActionPerformed

    private void btnUsuCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuCRUDActionPerformed
        PanelUsuarios panel = new PanelUsuarios(miVentana);
        
        miVentana.cambiarPanel(panel);
    }//GEN-LAST:event_btnUsuCRUDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPregCRUD;
    private javax.swing.JButton btnUsuCRUD;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
