/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package preguntasTest.vista;

import preguntasTest.gestion.GestionPreguntas;

/**
 *
 * @author Dam
 */
public class PanelFinal extends javax.swing.JPanel {
    private VentanaPreguntasTest miVentana;
    private GestionPreguntas gestion;
    
    /**
     * Creates new form panelFinal
     */
    public PanelFinal(VentanaPreguntasTest miVentana, Integer numAciertos) {
        initComponents();
        
        this.miVentana = miVentana;
        gestion = new GestionPreguntas();
        
        lblAciertos.setText("Número de aciertos: " + numAciertos + " de " + gestion.numPreguntas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAciertos = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 384));
        setMinimumSize(new java.awt.Dimension(400, 384));
        setPreferredSize(new java.awt.Dimension(400, 384));

        lblAciertos.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblAciertos.setText("Número de aciertos: ");
        lblAciertos.setName("lblAciertos"); // NOI18N

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblAciertos)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(lblAciertos)
                .addGap(106, 106, 106)
                .addComponent(btnSalir)
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAciertos;
    // End of variables declaration//GEN-END:variables
}
